version: '3'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=admin
          - MYSQL_ROOT_PASSWORD=admin
          - MYSQL_DATABASE=my_db
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./db:/docker-entrypoint-initdb.d/
        ports:
            - "3306:3306"
    app:
        build: ./app
        restart: always
        links: 
            - db
        ports:
            - "5000:5000"