version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
    db:
        image: mysql/mysql-server:latest
        restart: on-failure
        ports:
            - "3306:3306"
