version: '3'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=admin
          - MYSQL_ROOT_PASSWORD=admin
          - MYSQL_DATABASE=my_db
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./db:/docker-entrypoint-initdb.d/
        ports:
            - "3306:3306"
    app:
        build: ./app
        restart: always
        links: 
            - db
        ports:
            - "5000:5000"
        depends_on:
            - db
            - redis
    redis:
        image: "redis:5.0.4-stretch"
#         restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
#         stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
        volumes:
          - "redis:/data"
#         image: "redis"
#         restart: always
#         volumes:
#          - ./storage/redis/data:/data

    rq-worker:
        build: ./redis
        restart: always
        depends_on:
            - redis
        deploy:
          replicas: 3
         
volumes:
  redis: {}